### ISSUE TITLE
Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'links' can't have a default value

### ISSUE THREAD

**Issue by Yu-Chieh-Henry-Yang** [DMPRoadmap/roadmap#1569]
Hi,
When doing `rake db:schema:load` according to the instruction on GitHub home page, the migration step gives error.

**Expected behaviour:**
expect migrations to run without fail

**Actual behaviour:**
migration failed, producing this output:

```
-- create_table("orgs", {:force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'links' can't have a default value: CREATE TABLE `orgs` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255), `abbreviation` varchar(255), `target_url` varchar(255), `wayfless_entity` varchar(255), `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `parent_id` int(11), `is_other` tinyint(1), `sort_name` varchar(255), `banner_text` text, `logo_file_name` varchar(255), `region_id` int(11), `language_id` int(11), `logo_uid` varchar(255), `logo_name` varchar(255), `contact_email` varchar(255), `org_type` int(11) DEFAULT 0 NOT NULL, `links` text DEFAULT '{\"org\":[]}', `contact_name` varchar(255), `feedback_enabled` tinyint(1) DEFAULT 0, `feedback_email_subject` varchar(255), `feedback_email_msg` text) ENGINE=InnoDB
```

and 

```Caused by:
Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'links' can't have a default value
```

**Steps to reproduce:**
Follow GitHub home page instruction to setup a brand new app.

Notes:
1) https://github.com/DMPRoadmap/roadmap/releases/tag/v1.0.1 mentioned this, shouldn't it be fixed already? Or is this a different issue?
2) My Ruby and MySQL version:
```
$ mysql --version
mysql  Ver 15.1 Distrib 10.2.10-MariaDB, for osx10.13 (x86_64) using readline 5.1
$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
```
3) It seems like this issue is recognized in https://github.com/DMPRoadmap/roadmap/issues/85 and https://github.com/DMPRoadmap/roadmap/pull/1392

**Comment by xsrust** [comment]
Hi,
It looks like in the issues you referenced, we fixed the migration files, but that the default remains schema.rb file.  Since `rake db:schema:load` will create a db based off the schema.rb, this is causing an issue.

Likely one of the developer's db's still has this default and it's getting written out to schema.rb when they run migrations.  We'll talk about a strategy for ensuring this dosent happen going forward.

In the meantime, Simply remove the default on the org.links and try running again, everything should work.  Alternatively, consider switching to [Postgres](https://www.postgresql.org/) which supports defaults.

**Comment by briri** [comment]
Reopening this so we remember to update the schema.rb to remove the defaults

**Comment by briri** [comment]
schema was updated. nothing to UAT

**Comment by nicolasfranck** [comment]
The defaults are still present in branch `tags/v1.0.0`..
I spotted this when trying to migrate from DMPOnline_v4
