### ISSUE TITLE
Account creation error

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#271]
I shared a plan with a my personal account and was prompted to enter a password for my new account when I followed the link to view this. The following error was displayed, though logging in with my personal email and the password I set shows that the account was created nonetheless.
![picture1](https://cloud.githubusercontent.com/assets/6169940/25389943/e09bed00-29c9-11e7-8bf3-ef222a6176b2.png)

On reflection, I wonder if this error occurred as the email had been known by the system at some point. Last week I had changed my account name to my personal email under edit profile and have since switched it back. Perhaps the trace of that threw the error?

**Comment by vyruss** [comment]
Not a bug. Installation-specific, needs a few configuration tweaks

**Comment by briri** [comment]
where did the issue occur? dmponline-test or roadmap-stg and what config settings @vyruss ? An invalid token error sounds like the token has a lifespan and the login attempt was outside that boundary

**Comment by sjDCC** [comment]
This occurred on roadmap-stg. I think it may be because I had used that email temporarily. I had changed my account to that last week in testing and mis-remembered that, hence getting locked out when I uninstalled firefox and no longer had login details saved. I had changed it back so sent share plan invite to personal email today.

**Comment by briri** [comment]
ok. I'll see if we can replicate it

**Comment by vyruss** [comment]
Whoops, I assumed it was the wrong hostname issue (which isn't set up properly on dmponline-test yet). @briri I'm referring to `config/environments/production.rb`: 
```ruby
config.action_mailer.default_url_options = { :host => 'my.hostname.here' }
```

**Comment by vyruss** [comment]
After investigation, appears to be subcase of #287. For some reason it tries to update_without_password when setting the (invited) user's password upon sign-up.

**Comment by sjDCC** [comment]
I've tried sharing a plan with an account that has already been created in the system but not yet validated and didn't get an error so I think this is now fixed on DMPonline. I couldn't full test on DMPRoadmap staging. I think you're maybe one PR behind @briri as the message text in the sharing email was different and the link didn't resolve. 
![roadmap-staging](https://cloud.githubusercontent.com/assets/6169940/26110035/04f1f840-3a49-11e7-91fa-3be94116e8a4.PNG)

**Comment by stephaniesimms** [comment]
Things should be in sync now as @briri just deployed the latest code to roadmap-stage. I observed the same thing you describe above @sjDCC - no error message but the email text is missing the plan owner name and the link does not resolve (screenshot below).

![screen shot 2017-05-16 at 10 24 43 am](https://cloud.githubusercontent.com/assets/12703638/26119530/59f5d9be-3a22-11e7-9c5f-0cbb6b356c95.png)

**Comment by briri** [comment]
which of the links is not resolving?

**Comment by briri** [comment]
The email template uses the user's firstname and surname but those fields are likely blank in this scenario hence the '"DCC guidance test (NIH template)" by .'

If we switch it to use `name` instead it will display the email address there if the name is not available.

**Comment by vyruss** [comment]
@briri let's fall back on the email if First name or Surname is empty

**Comment by briri** [comment]
ok. its ready for you in the PR with the change to when a template version is created

**Comment by sjDCC** [comment]
Hey @briri The link that gave an error for me was "Click here" to accept the invitation...

**Comment by sjDCC** [comment]
This is all working on DMPonline test. Just leaving open for now so @stephaniesimms can check all ok on staging and then close

**Comment by stephaniesimms** [comment]
this appears to be working as expected but I'm leaving it open for now because new issues have been introduced that prevent me from testing the entire workflow. i now get an error message when signing out of the system to accept the invitation, which appears to be related to some Shib configuration (screenshot below)

![screen shot 2017-05-31 at 3 29 10 pm](https://cloud.githubusercontent.com/assets/12703638/26656925/f5b6783c-4615-11e7-8eba-3000e3760f42.png)

**Comment by briri** [comment]
this logout issue may be due to shib not being configured properly on stage. I think this must be new, we did not call the shib logout in the past. 
We got shib working on dev today. I'll set aside some time to set it up on stage tomorrow

**Comment by stephaniesimms** [comment]
@sjdcc can you confirm this is ok? Update email title for inviting a user to contribute to a plan who does not yet have an new account:

Email title: A Data Management Plan in [TOOL NAME] has been shared with you

**Comment by vyruss** [comment]
@stephaniesimms I just made the title the same (Commit 95d4bb70ef6b0dbbb848f97c4a3b0268b6712d87 )

**Comment by sjDCC** [comment]
Yes, looks good.

**Comment by stephaniesimms** [comment]
The process works as expected and revised email looks good. Closing issue.
