### ISSUE TITLE
Cannot create plan if No Org and No Funder

### ISSUE THREAD

**Issue by stephaniesimms** [DMPRoadmap/roadmap#285]
When I have no Org affiliation and try to create a new plan by selecting 'No Funder' I get the following error (screenshot). Expected behavior is to provide the default DCC template.

Related issues #257 and #267 (closed)

![no-funder-no-org](https://cloud.githubusercontent.com/assets/12703638/25587874/d0f0983e-2e5a-11e7-9afc-74dd3c7ac3fc.png)

**Comment by vyruss** [comment]
Fixed by latest PR

**Comment by dsisu** [comment]
This works for me

**Comment by sjDCC** [comment]
This appears to work as the plan creates, but you can't edit anything. On staging when I click to edit the plan I get the following error.
![error](https://cloud.githubusercontent.com/assets/6169940/26302083/042bd9f8-3edb-11e7-98d6-19e75c546e4b.PNG)
![view-dmp](https://cloud.githubusercontent.com/assets/6169940/26302084/04448d18-3edb-11e7-82fa-538fbba6f244.PNG)

On DMPonline it's a worse error. No phase / DMP appears at all.
![dmponline-test](https://cloud.githubusercontent.com/assets/6169940/26302133/29d19c10-3edb-11e7-800a-b12ecec52f2a.PNG)

I've tried digging around on the admin side to see what's going wrong as I suspect it's a template error. This uncovered more things. When I vie the Tuuli (default) template on roadmap staging, I can't edit or view any of the versions. All give a "something went wrong error"
![roadmap-tuuli](https://cloud.githubusercontent.com/assets/6169940/26302344/ce6c4996-3edb-11e7-8e87-fdde1efe136e.PNG)

I tried changing my institutional affiliation to Helsinki uni to see if it was just an issue with the default template and that gave a stranger issue. It was showing a GU template. Checking the Tuuli live site, the helsinki template is called general data management so not sure where this has come from.

![tuuli-live](https://cloud.githubusercontent.com/assets/6169940/26302482/48ec8280-3edc-11e7-8745-d3c4915838ef.PNG)

![view-helsinki-template](https://cloud.githubusercontent.com/assets/6169940/26302532/792aeea0-3edc-11e7-87e6-adf331e4ff36.PNG)

Checking the DMPonline default template, this indicates it is published. Viewing the history table there are two versions, The first is unpublished and weirdly has no phase / set of questions. The supposedly published one is showing as unpublished here and gives a 404 if you click to view the plan/template. 
![dmponline-default](https://cloud.githubusercontent.com/assets/6169940/26302778/49e56fc0-3edd-11e7-9976-e3c56e182385.PNG)
![no-phase](https://cloud.githubusercontent.com/assets/6169940/26302785/4f939fc8-3edd-11e7-8a11-ed85fc70de58.PNG)
![whatever](https://cloud.githubusercontent.com/assets/6169940/26302790/539d6b76-3edd-11e7-97a5-29f23072a5c2.PNG)

I really can't figure out what's gone wrong here, but I think data has gone mixed up

**Comment by stephaniesimms** [comment]
we noted a few weeks back that there are still some issues with the data migration and it's difficult to distinguish between issues produced by bad data and those produced by bugs in the system. you might try testing the migration @sjDCC before attempting to disentangle things here.

**Comment by sjDCC** [comment]
This is still not working. 

If I create a plan with no funder and no org, it tells me it has successfully created based on the generic template but no DMP content displays. I think this is linked with the various template tickets so moving back to in progress to pull back through to test again once these are deployed

![still-not-working](https://cloud.githubusercontent.com/assets/6169940/26487554/ddd68684-41f7-11e7-992c-59be3cb625ac.PNG)

**Comment by vyruss** [comment]
I cannot replicate this. Steps:
1. I change my profile to have no org, 
2. I create plan, ticking "no research organisation" and "no funder" 
3. I can edit "Generic DMP"

**Comment by sjDCC** [comment]
This is working now. Closing out
